# Generated by Django 5.0.4 on 2024-04-18 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinToss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=5)),
                ('date_thrown', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
